### ISSUE TITLE
Problems running circlator

### ISSUE THREAD

**Issue by jhernandez1409** [sanger-pathogens/circlator#97]
Hi, 
I installed circlator from here (github) and after installing all the dependencies listed here I ran 'circlator progcheck' but this is the error I keep getting and I have tried a lot of things including reinstalling all the dependencies and nothing seems to work. Help please!

Circlator version: 1.5.1

External dependencies:
WARNING: Didn't find bwa in path. Looked for:bwa
WARNING: Didn't find canu in path. Looked for:canu
nucmer	3.1	/usr/bin/nucmer
WARNING: Didn't find prodigal in path. Looked for:prodigal
samtools	0.1.19	/usr/bin/samtools
WARNING: Didn't find spades in path. Looked for:spades.py

Python version:
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

Python dependencies:
openpyxl	2.4.8	/home/jojo/.local/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq	3.15.0	/usr/local/lib/python3.5/dist-packages/pyfastaq-3.15.0-py3.5.egg/pyfastaq/__init__.py
pymummer	0.10.2	/usr/local/lib/python3.5/dist-packages/pymummer-0.10.2-py3.5.egg/pymummer/__init__.py
pysam	0.11.2.2	/home/jojo/.local/lib/python3.5/site-packages/pysam/__init__.py

Thanks in advance,

JoJo

**Comment by yjx1217** [comment]
Hi JoJo,

It seems that the problem lies in Circlator cannot detect those tools in your $PATH environment viriable. If you correctly add the full path to those tools to your $PATH, the problem should be solved. 

You can check this link for the details on setting $PATH.

Best,
Jia-Xing

**Comment by jhernandez1409** [comment]
Hi Jia-Xing

Thank you for replying. I did the following to set up the tools to my $PATH, and I did it for all the dependencies and tried multiple times but it didn't work:

export PATH=$PATH:/home/jojo/Desktop/Software_Bioinformatics/canu-1.5 

Do you know another way I should do it?

Thanks,

JoJo

**Comment by yjx1217** [comment]
Hi JoJo,

You need to add the full path to the binary files, for example, for canu it will be:
export PATH=$PATH:/home/jojo/Desktop/Software_Bioinformatics/canu-1.5/Linux-amd64/bin

Best,
Jia-Xing

**Comment by martinghunt** [comment]
Thanks @yjx1217 for the helpful comments!

@jhernandez1409 just to expand a bit: you can test if the depenencies are installed by just trying to run them. e.g. just running:

    bwa

should work and print the help, and not give an error like `bwa: command not found`.

**Comment by jhernandez1409** [comment]
Thank you Jia-Xing and Martin! However, I dont understand why I still have problems. Below is the output when I tried to run circlator, just in case you guys can help me with this. Thanks for all your help.

JoJo

Checking external programs __________________________
Circlator version: 1.5.1

External dependencies:
bwa	0.7.12	/usr/bin/bwa
canu	1.5	/home/jojo/Desktop/Software_Bioinformatics/canu-1.5/Linux-amd64/bin/canu
nucmer	3.1	/usr/bin/nucmer
prodigal	2.50	/home/jojo/Desktop/Software_Bioinformatics/prodigal.v2_50/prodigal
samtools	0.1.19	/usr/bin/samtools
spades	3.7.1	/home/jojo/Desktop/Software_Bioinformatics/SPAdes-3.7.1/spades.py

Python version:
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

Python dependencies:
openpyxl	2.4.8	/home/jojo/.local/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq	3.15.0	/usr/local/lib/python3.5/dist-packages/pyfastaq-3.15.0-py3.5.egg/pyfastaq/__init__.py
pymummer	0.10.2	/usr/local/lib/python3.5/dist-packages/pymummer-0.10.2-py3.5.egg/pymummer/__init__.py
pysam	0.11.2.2	/home/jojo/.local/lib/python3.5/site-packages/pysam/__init__.py
______________________________ Running mapreads _______________________________
samtools	0.1.19	/usr/bin/samtools
bwa	0.7.12	/usr/bin/bwa
syscall: bwa index -p 01.mapreads.bam.tmp.bwa_index 00.input_assembly.fasta
syscall: bwa mem -x pacbio -t 8 01.mapreads.bam.tmp.bwa_index /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/Canu_output_JoJo5_all_sensitive/JoJo5_all_canu_output_sensitive.correctedReads.fasta.gz | samtools view -F 0x0800 -T 00.input_assembly.fasta -b -o 01.mapreads.bam.tmp.unsorted.bam -
syscall: samtools sort -@ 4 -m 125M 01.mapreads.bam.tmp.unsorted.bam  01.mapreads
syscall: samtools index 01.mapreads.bam
______________________________ Running bam2reads ______________________________
Getting reads from BAM file /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/01.mapreads.bam
Getting all reads that map to ends of contig tig00000004. Coords: 1-50000;113973-163972
Getting all reads that map to contig tig00000009
Getting all reads that map to ends of contig tig00000015. Coords: 1-50000;869169-919168
Getting all reads that map to contig tig00000016
Getting all reads that map to ends of contig tig00000017. Coords: 1-50000;3884692-3934691
Getting all unmapped reads
Finished getting reads.
Log file: /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.log
Reads file: /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta
______________________________ Running assemble _______________________________
samtools	0.1.19	/usr/bin/samtools
spades	3.7.1	/home/jojo/Desktop/Software_Bioinformatics/SPAdes-3.7.1/spades.py
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.127.zeb7_gd1 -t 8 -k 127 --careful --only-assembler
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.117.ddvu2q7j -t 8 -k 117 --careful --only-assembler
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.107.hr_inz0d -t 8 -k 107 --careful --only-assembler
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.97.t5_78vps -t 8 -k 97 --careful --only-assembler
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.87.q72zgun8 -t 8 -k 87 --careful --only-assembler
syscall: spades.py -s /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/02.bam2reads.fasta -o /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.77.apbx_71_ -t 8 -k 77 --careful --only-assembler
Traceback (most recent call last):
  File "/home/jojo/Desktop/Software_Bioinformatics/circlator-1.5.1/scripts/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.1-py3.5.egg/circlator/tasks/all.py", line 169, in run
    a.run()
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.1-py3.5.egg/circlator/assemble.py", line 176, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.1-py3.5.egg/circlator/assemble.py", line 145, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.97.t5_78vps
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.117.ddvu2q7j
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.87.q72zgun8
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.107.hr_inz0d
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.77.apbx_71_
  /home/jojo/Desktop/Lab/Guatemala/Pacbio_Data/circlator_output/circlatorJoJo5all_sensitive/03.assemble.tmp.spades.127.zeb7_gd1
The reason why should be in the spades.log file in each directory.
